version: "3"

services:
  ray-head:
    image: rayproject/ray:2.3.0-py310
    ports:
      - 8265:8265 
      - 6379:6379
      - 10001:10001
    command: bash -c "ray start --head --dashboard-port=8265 --port=6379 --dashboard-host=0.0.0.0 --redis-password=changeit --block"
    shm_size: 2g
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2g'

  ray-worker:
    image: rayproject/ray:2.3.0-py310
    depends_on: 
      - ray-head
    command: bash -c "ray start --address=ray-head:6379 --redis-password=changeit --num-cpus=1 --block" 
    shm_size: 2g
    deploy:
      mode: replicated
      replicas: 3 
      resources:
        limits:
          cpus: '1'
          memory: '2g'