apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: lab2-rest-hw:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: JWT_TOKEN_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: jwt-token-secret-key
            - name: ACCUWEATHER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: accuweather-api-key
            - name: USE_CACHE
              value: "true"
            - name: REDIS_URL
              value: "redis://my-app-redis-headless:6379/0"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-app-redis
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app-redis
  serviceName: my-app-redis-headless
  template:
    metadata:
      labels:
        app: my-app-redis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-redis
spec:
  selector:
    app: my-app-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-redis-headless
spec:
  selector:
    app: my-app-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  clusterIP: None
  publishNotReadyAddresses: true
