version: '2'
services:
  app:
    image: lab2-rest-hw
    build: .
    ports:
      - "8000:80"
    environment:
      - JWT_TOKEN_SECRET_KEY
      - ACCUWEATHER_API_KEY
      - USE_CACHE
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
  redis:
    image: redis/redis-stack:latest
